#!/usr/bin/env python3
"""Stateful-reasoning probe: copy / reverse / cipher / sum on held-out docs.

Docs are generated by the same `v7.data._build_reason_doc` as training but from a
fresh seed (held-out), optionally with filler sentences spliced between the task
and the answer so the model must hold intermediate state in the hidden layer
across the gap — the O(1)-memory analogue of the recall suite.

Scoring: greedy argmax over the answer token span; token-level exact accuracy
aggregated per (gap, task).
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from v7.data import _RECALL_FILLER_BANK, _build_reason_doc  # noqa: E402
from run_memory_behavioral import (  # noqa: E402  (sibling module)
    _last_logits, _load_hf, _load_transformer, _load_v11, _load_v13,
)

ANSWER_MARKER = 'Answer: '


def make_probe_doc(rng: random.Random, gap_sentences: int) -> dict[str, Any]:
    """One held-out reasoning doc with `gap_sentences` filler splices.

    gap=0 -> doc is exactly the generator's doc.
    gap>0 -> filler sentences are spliced before the answer line, so the model
    must carry the task state across the filler.
    """
    doc = _build_reason_doc(rng)
    head, answer = doc.split(ANSWER_MARKER)
    if gap_sentences > 0:
        filler = ' '.join(rng.choice(_RECALL_FILLER_BANK)
                          for _ in range(gap_sentences))
        body = f"{head}Filler: {filler}\n{ANSWER_MARKER}"
    else:
        body = f"{head}{ANSWER_MARKER}"
    task_key = head.split(':', 1)[1].split('\n')[0].strip().rstrip('.')
    if task_key.startswith('encode with a Caesar shift'):
        task_key = 'Caesar cipher'
    elif 'reverse order' in task_key:
        task_key = 'reverse copy'
    elif 'repeat' in task_key:
        task_key = 'copy'
    elif task_key.startswith('give the sum'):
        task_key = 'digit sum'
    return {'prompt': body, 'answer': answer, 'task': task_key}


@torch.inference_mode()
def score_doc_argmax(model_type: str, model, tokenizer, doc: dict[str, Any],
                     device: torch.device) -> tuple[int, int]:
    """Greedy-argmax over the answer span; returns (correct, total)."""
    prompt_ids = tokenizer.encode(doc['prompt'], add_special_tokens=False)
    answer_ids = tokenizer.encode(doc['answer'], add_special_tokens=False)
    correct = 0
    prefix = list(prompt_ids)
    for tok in answer_ids:
        ctx = torch.tensor([prefix], dtype=torch.long, device=device)
        logit = _last_logits(model_type, model, ctx)
        if torch.isfinite(logit).all():
            correct += 1.0 if int(logit.argmax()) == tok else 0.0
        prefix.append(tok)
    return correct, len(answer_ids)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description='Stateful reasoning probe')
    p.add_argument('--model-type', choices=('v11', 'v13', 'transformer', 'hf'),
                   required=True)
    p.add_argument('--checkpoint', type=Path)
    p.add_argument('--model-id', default='state-spaces/mamba-130m-hf')
    p.add_argument('--preset', default='v13_micro_10m_recall')
    p.add_argument('--tasks-per-cell', type=int, default=20)
    p.add_argument('--gaps', type=str, default='0,2,5',
                   help='Comma list of filler-sentence counts (0 = no gap)')
    p.add_argument('--seed', type=int, default=20260819,
                   help='Held-out doc seed (distinct from mix_seed=42)')
    p.add_argument('--output', type=Path, required=True)
    return p


def main() -> int:
    args = build_parser().parse_args()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    gaps = tuple(int(x) for x in args.gaps.split(',') if x.strip() != '')

    if args.model_type == 'v13':
        model, tokenizer, _ = _load_v13(args.checkpoint, args.preset, device)
    elif args.model_type == 'v11':
        model, tokenizer, _ = _load_v11(args.checkpoint, args.preset, device)
    elif args.model_type == 'transformer':
        model, tokenizer, _ = _load_transformer(args.checkpoint, device)
    else:
        model, tokenizer, _ = _load_hf(args.model_id, device)

    rows = []
    per_cell: dict[tuple, list[float]] = defaultdict(list)
    per_task: dict[str, list[float]] = defaultdict(list)
    total_cells = len(gaps) * args.tasks_per_cell
    done = 0
    for gap in gaps:
        for i in range(args.tasks_per_cell):
            rng = random.Random(args.seed * 1000 + gap * 100 + i)
            doc = make_probe_doc(rng, gap)
            c, n = score_doc_argmax(args.model_type, model, tokenizer,
                                    doc, device)
            acc = c / n
            per_cell[(gap, doc['task'])].append(acc)
            per_task[doc['task']].append(acc)
            rows.append({'gap': gap, 'task': doc['task'], 'acc': acc,
                         'correct': c, 'total': n,
                         'prompt': doc['prompt'][:200], 'answer': doc['answer']})
            done += 1
            print(f'  [{done}/{total_cells}] gap={gap} '
                  f'task={doc["task"][:20]:<20} acc={acc:.2f} ({c}/{n})',
                  flush=True)

    summary = [{'gap': gap, 'task': task, 'n': len(accs),
                'acc': float(sum(accs) / len(accs))}
               for (gap, task), accs in sorted(per_cell.items())]
    per_task_summary = {k: {'n': len(v), 'acc': float(sum(v) / len(v))}
                        for k, v in sorted(per_task.items())}

    out = {
        'model_type': args.model_type,
        'checkpoint': str(args.checkpoint or args.model_id),
        'seed': args.seed,
        'gaps': list(gaps),
        'tasks_per_cell': args.tasks_per_cell,
        'timestamp': datetime.now(timezone.utc).isoformat(),
        'per_cell': summary,
        'per_task': per_task_summary,
        'rows': rows,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(out, indent=2))

    print('\n' + '=' * 60)
    print(f"Reasoning probe ({args.model_type}) — token-exact acc")
    print(f"{'gap':>5} {'task':<22} {'acc':>7} {'n':>4}")
    for s in summary:
        print(f"{s['gap']:>5} {s['task'][:22]:<22} {s['acc']:>7.2f} {s['n']:>4}")
    print(f"Wrote {args.output}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
